name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # actions/checkout@v4.4.0
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      # actions/setup-go@v5.6.0
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff
        with:
          go-version-file: go.mod
          cache: true

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Lint
        # golangci/golangci-lint-action@v7.0.1
        uses: golangci/golangci-lint-action@9fae48acfc02a90574d7c304a1758ef9895495fa
        with:
          version: v2.13.2

      - name: Lint Dockerfile
        # hadolint/hadolint-action@v3.5.0
        uses: hadolint/hadolint-action@06be81baf89a55ffd0e24b8f04a4185738dd3387
        with:
          dockerfile: Dockerfile
          failure-threshold: error
